ARG PYTHON_VERSION="3.11"

FROM python:${PYTHON_VERSION}
ARG PYTHON_VERSION
ARG PY="python${PYTHON_VERSION}"

ENV PYTHON_VERSION=$PYTHON_VERSION

WORKDIR /app

RUN ${PY} -m pip install --upgrade pip

COPY requirements.36.txt .
RUN ${PY} -m pip install -r requirements.36.txt

# need rpqueue
COPY rpqueue/*.py rpqueue/
# and need the tests too
COPY tests/* rpqueue_tests/

# Note: needs access to Valkey
CMD $PY -m rpqueue_tests.test_rpqueue
