version: '3.9'
services:
  rpqueue-test-3-11:
    build:
      context: .
      dockerfile: Dockerfile.3.11
    environment:
      REDIS_HOST: redis-task-broker
      REDIS_PORT: 6379
      REDIS_DB: 15
      PYTHONPATH: /app
    links:
      - redis-task-broker
  redis-task-broker:
    image: redis:7-bullseye
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save ""
