FROM python:3.11-bullseye

WORKDIR /app

COPY requirements.txt .

RUN python3.11 -m pip install -r requirements.txt
RUN python3.11 -m pip install sphinx twine

# need rpqueue
COPY rpqueue/*.py rpqueue/
# and need the tests too
COPY tests/* rpqueue_tests/
# and the sphinx stuff in

COPY conf.py .
COPY VERSION .
COPY index.rst .
COPY README.rst .


# Note: needs access to Redis; assumes localhost:6879
CMD ["python3.11", "-m", "rpqueue_tests.test_rpqueue"]
