version: '3.9'
services:
  rpqueue-test-docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    environment:
      REDIS_HOST: redis-task-broker
      REDIS_PORT: 6379
      REDIS_DB: 15
      PYTHONPATH: /app
    volumes:
      - /home/josiah/open-source/rpqueue/_build/html/:/app/_build/html:rw
