FROM python:3.7-bullseye

WORKDIR /app

COPY requirements.txt .

RUN python3.7 -m pip install -r requirements.txt

# need rpqueue
COPY rpqueue/*.py rpqueue/
# and need the tests too
COPY tests/* rpqueue_tests/

# Note: needs access to Redis; assumes localhost:6879
CMD ["python3.7", "-m", "rpqueue_tests.test_rpqueue"]
